---
# tasks file for prometheus-container
    - name: Start Prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus
        ports:
          - "9090:9090"
        volumes: 
          - <path/to/file>
        restart_policy: always
